### ISSUE TITLE
Will be there a guide ?

### ISSUE THREAD

**Issue by MajeedJJ** [paddlesteamer/superonline_hg253s#3]
Hi

I've read your article more than once, it has an interesting approach on how to solve many issues people are facing nowadays in regard of taking what is yours. I've tried applying what was in the article but i seem to fail measurably. i was wondering if there will be a guide or more basic approach to implement what was presented in the article mentioned above. I am in real interest of what you have accomplished.

Thanks for the amazing findings.

**Comment by paddlesteamer** [comment]
Unfortunately, I'm not planning to release any guide but I think blog posts should be enough.
